version: 0.2
phases:
  pre_build:
    commands:
      echo Restore started on `date`
      dotnet restore ToyRobotSimulator.csproj
  build:
    commands:
      echo Build started on `date`
      dotnet publish -c release -o ./build_output ToyRobotSimulator.csproj
artifacts:
  files:
    ToyRobotSimulator/build_output/**/*
